### ISSUE TITLE
Notifier stays offline despite regaining connection

### ISSUE THREAD

**Issue by benrondeau** [sindresorhus/notifier-for-github-chrome#132]
When Chrome goes offline and the extension looses connection to Github, it shows a yellow text bubble saying `off` (or something similar). When you regain internet connection, this bubble stays in place and the only way to reconnect is to manually click on the plugin icon. I have had the plugin be in 'offline' mode for long periods of time and therefore missed notifications.

Ideally, the plugin would re-connect itself and not require the user to click on the plugin icon to reconnect to Github. Not very familiar with the Chrome API but if it does not expose a method to be notified upon regaining internet connection, something like a `setTimeout` that pings the URL every 5 seconds until a connection could be another solution.

@sindresorhus Any thoughts? I will create a PR if you will accept it.

**Comment by EvertEt** [comment]
Should be working since https://github.com/sindresorhus/notifier-for-github-chrome/pull/123 due to the  `window.addEventListener`.

**Comment by benrondeau** [comment]
This is not working for me, unfortunately. I have not investigated specifically why, but it does not work with my setup:

```
Google Chrome Version v58.0.3029.110 (64-bit)
Notifier for GitHub v3.0.3
Mac OSX 10.12.5
```

It will stay offline for as long as I let it. I put my computer to sleep numerous times throughout the day and when I come back, I have to manually reconnect the plugin (clicking on the icon).

**Comment by benrondeau** [comment]
Upgraded to `Google Chrome v59.0.3071.86 (Official Build) (64-bit)` and the problem still exists.

**Comment by sgrjyb** [comment]
Has been updated to https://github.com/sindresorhus/notifier-for-github-chrome/archive/3.0.4.zip

**Comment by benrondeau** [comment]
@sindresorhus Some issues with 3.0.4 release:

- [ ] You didn't update the manifest version from `3.0.3` to `3.0.4`
- [ ] This extension seems to have issues is Chrome 56 (see image below)

<img width="584" alt="screen shot 2017-06-08 at 11 35 02 pm" src="https://user-images.githubusercontent.com/5001219/26961300-5e355eda-4ca3-11e7-9a85-d31cbfe4beac.png">

- [ ] Manually installing 3.0.4 gives this error:

<img width="726" alt="screen shot 2017-06-08 at 11 35 25 pm" src="https://user-images.githubusercontent.com/5001219/26961308-70682f7e-4ca3-11e7-90db-61b383f2bed3.png">

**Comment by gcochard** [comment]
@benrondeau make sure to build the extension with `npm run build` before trying to load it if you haven't already done that.

**Comment by benrondeau** [comment]
@gcochard Thanks. I installed it and got this notification:

<img width="742" alt="screen shot 2017-06-08 at 11 51 49 pm" src="https://user-images.githubusercontent.com/5001219/26961602-983dd2fe-4ca5-11e7-8e7f-7cc99491bc75.png">

**Comment by ExE-Boss** [comment]
@benrondeau @EvertEt#129 That is tracked by Chromium [Bug 677855](https://bugs.chromium.org/p/chromium/issues/detail?id=677855 "Extensions manifest should recognize “applications” key") [(**Status:** WontFix)](https://bugs.chromium.org/p/chromium/issues/detail?id=677855 "You had one job, Google. ONE JOB!"), but otherwise the extension works fine.

**Comment by midenok** [comment]
Reproduces for me. The extension don't work for more than half-year.

```
Google Chrome Version 55.0.2883.87 (64-bit)
Notifier for GitHub 3.0.5
```

**Comment by jakeonrails** [comment]
I'm on 3.0.5 and when I go back and forth between work and home the extension is "OFF" and I have to click to turn it on again. Can it be made to just automatically connect when the browser is first opened instead?

**Comment by sindresorhus** [comment]
Yes, we should get this fixed.

---

> *Note: This issue has a bounty, so it's expected that you are an experienced programmer and that you give it your best effort if you intend to tackle this. Don't forget, if applicable, to add tests, docs (double-check for typos), and update TypeScript definitions. And don't be sloppy. Review your own diff multiple times and try to find ways to improve and simplify your code. Instead of asking too many questions, present solutions. The point of an issue bounty is to reduce my workload, not give me more. Thanks for helping out 🙌*
